#include "LIB/STD_TYPES.h"
#include "LIB/BIT_MATH.h"
#include "RCC_Init.h"
#include "GPIO_Init.h"

int main(void)
{
	/* Initialize The System Clock */
	RCC_VidInit();
	/*Enable Clock RCC for GPIOA */
	RCC_VidEnableClock(RCC_APB2,RCC_APB2_IOPA);
	/*Enable Clock RCC for GPIOB */
	RCC_VidEnableClock(RCC_APB2,RCC_APB2_IOPB);
	/*Enable Clock RCC for GPIOC */
	RCC_VidEnableClock(RCC_APB2,RCC_APB2_IOPC);
	/*PINA0 OUTPUT PP 10MHz */
	/*GPIO_VidSetPinDirection(GPIO_PORTB , GPIO_PIN0 ,GPIO_OUTPUT_SPEED_10M_PP );
	GPIO_VidSetPinValue(GPIO_PORTB , GPIO_PIN0 , GPIO_HIGH);

	GPIO_VidSetPinDirection(GPIO_PORTB , GPIO_PIN1 ,GPIO_OUTPUT_SPEED_10M_PP );
	GPIO_VidSetPinValue(GPIO_PORTB , GPIO_PIN1 , GPIO_HIGH);

	GPIO_VidSetPinDirection(GPIO_PORTB , GPIO_PIN2 ,GPIO_OUTPUT_SPEED_10M_PP );
	GPIO_VidSetPinValue(GPIO_PORTB , GPIO_PIN2 , GPIO_HIGH);

	GPIO_VidSetPinDirection(GPIO_PORTB , GPIO_PIN3 ,GPIO_OUTPUT_SPEED_10M_PP );
	GPIO_VidSetPinValue(GPIO_PORTB , GPIO_PIN3 , GPIO_HIGH);

	GPIO_VidSetPinDirection(GPIO_PORTB , GPIO_PIN4 ,GPIO_OUTPUT_SPEED_10M_PP );
	GPIO_VidSetPinValue(GPIO_PORTB , GPIO_PIN4 , GPIO_HIGH);

	GPIO_VidSetPinDirection(GPIO_PORTB , GPIO_PIN5 ,GPIO_OUTPUT_SPEED_10M_PP );
	GPIO_VidSetPinValue(GPIO_PORTB , GPIO_PIN5 , GPIO_HIGH);

	GPIO_VidSetPinDirection(GPIO_PORTB , GPIO_PIN6 ,GPIO_OUTPUT_SPEED_10M_PP );
	GPIO_VidSetPinValue(GPIO_PORTB , GPIO_PIN6 , GPIO_HIGH);

	GPIO_VidSetPinDirection(GPIO_PORTB , GPIO_PIN7 ,GPIO_OUTPUT_SPEED_10M_PP );
	GPIO_VidSetPinValue(GPIO_PORTB , GPIO_PIN7 , GPIO_HIGH);


	GPIO_VidSetPinDirection(GPIO_PORTB , GPIO_PIN8 ,GPIO_OUTPUT_SPEED_10M_PP );
	GPIO_VidSetPinValue(GPIO_PORTB , GPIO_PIN8 , GPIO_HIGH);

	GPIO_VidSetPinDirection(GPIO_PORTB , GPIO_PIN9 ,GPIO_OUTPUT_SPEED_10M_PP );
	GPIO_VidSetPinValue(GPIO_PORTB , GPIO_PIN9 , GPIO_HIGH);

	GPIO_VidSetPinDirection(GPIO_PORTB , GPIO_PIN10 ,GPIO_OUTPUT_SPEED_10M_PP );
	GPIO_VidSetPinValue(GPIO_PORTB , GPIO_PIN10 , GPIO_HIGH);

	GPIO_VidSetPinDirection(GPIO_PORTB , GPIO_PIN11 ,GPIO_OUTPUT_SPEED_10M_PP );
	GPIO_VidSetPinValue(GPIO_PORTB , GPIO_PIN11 , GPIO_HIGH);

	GPIO_VidSetPinDirection(GPIO_PORTB , GPIO_PIN12 ,GPIO_OUTPUT_SPEED_10M_PP );
	GPIO_VidSetPinValue(GPIO_PORTB , GPIO_PIN12 , GPIO_HIGH);

	GPIO_VidSetPinDirection(GPIO_PORTB , GPIO_PIN13 ,GPIO_OUTPUT_SPEED_10M_PP );
	GPIO_VidSetPinValue(GPIO_PORTB , GPIO_PIN13 , GPIO_HIGH);

	GPIO_VidSetPinDirection(GPIO_PORTB , GPIO_PIN14 ,GPIO_OUTPUT_SPEED_10M_PP );
	GPIO_VidSetPinValue(GPIO_PORTB , GPIO_PIN14 , GPIO_HIGH);

	GPIO_VidSetPinDirection(GPIO_PORTB , GPIO_PIN15 ,GPIO_OUTPUT_SPEED_10M_PP );
	GPIO_VidSetPinValue(GPIO_PORTB , GPIO_PIN15 , GPIO_HIGH);
*/

	GPIO_VidSetPortDirection( GPIO_PORTA, GPIO_OUTPUT_SPEED_10M_PP );
	GPIO_VidSetPortDirection( GPIO_PORTB, GPIO_OUTPUT_SPEED_10M_PP );

	GPIO_VidSetPortValue( GPIO_PORTA , 0xFFFF );
	GPIO_VidSetPortValue( GPIO_PORTB , 0xFFFF );
	while(1)
	{/*
		GPIO_VidSetPinValue(GPIO_PORTB , GPIO_PIN0 , GPIO_HIGH);
		for (u16 i=0; i<5000;i++){
			for(u16 j=0;j<5000;j++){
				asm("NOP");
			}
		}
		GPIO_VidSetPinValue(GPIO_PORTB , GPIO_PIN0 , GPIO_LOW);
		for (u16 i=0; i<5000;i++){
			for(u16 j=0;j<5000;j++){
				asm("NOP");
			}
		}*/
	}
	return 0;
}
